### ISSUE TITLE
CSGO Round Roadmap

### ISSUE THREAD

**Issue by TheSuperGAU** [antonpup/Aurora#560]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (CSGO)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The Overwolf App CSGO Indicator has a function that shows played rounds accross the F-Keys by colouring one green or red for each won or lost round, eventually displaying a "roadmap" of all played rounds on that side. I would love to have something like that in Aurora since otherwise it´s far superior to what that app can do.

### Actual behavior:
The only way I found yet for something similar was showing a percentage of won rounds for one side accross the keys by using CT/T won as percentage and 15 as max, but that doesn´t take into account the order of the rounds. I only downloaded the software yesterday, so if there is any way to do that I didn´t get i would appreciate somebody telling me how.

And thanks for this great software!
